FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get -y --no-install-recommends install \
    libpq-dev \
    build-essential \
    ca-certificates \
    openssl \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "notification_consumer_main.py"]