version: '3.9'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
    healthcheck:
      test: ["CMD-SHELL", "kafka-broker-api-versions --bootstrap-server localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  aggregator-parser:
    build: ./services/aggregator-parser-service
    ports:
      - "8000:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: raw_articles
    depends_on:
      kafka:
        condition: service_healthy

  news-site-parser:
    build: ./services/news-site-parser-service
    ports:
      - "8001:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: raw_articles
    depends_on:
      kafka:
        condition: service_healthy

  telegram-parser:
    build: ./services/telegram-parser-service
    ports:
      - "8002:8000"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: raw_articles
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy

  text-preprocessing:
    build: ./services/text-preprocessing-service
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      INPUT_TOPIC: raw_articles
      OUTPUT_TOPIC_NER: text_for_ner
      OUTPUT_TOPIC_RISK: text_for_risk
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    command: >
      sh -c "sleep 10 && python text_preprocessing_service_kafka.py"

  risk-classifier:
    build: ./services/risk-classifier
    env_file:
      - .env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: text_for_risk
      OUTPUT_TOPIC: risk_classified
     
    depends_on:
      kafka:
        condition: service_healthy
    restart: on-failure
    command: >
      sh -c "sleep 10 && python -c 'from app.kafka_consumer import consume_from_kafka; consume_from_kafka()'"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "password" ]

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  elasticsearch-sync:
    build: ./services/elasticsearch-sync
    env_file:
      - .env
    environment:
      POSTGRES_DB_URL: postgresql://news_db_r386_user:d3RdNiRIt1B1iWzamwc3Tblto5FxDpJz@dpg-d68bevrh46gs73fc7ln0-a.oregon-postgres.render.com/news_db_r386
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      elasticsearch:
        condition: service_healthy
    restart: on-failure
    command: python app/main.py

  output_module:
    build: ./services/output_module
    ports:
      - "8003:8000"
    env_file:
      - .env 
    depends_on:
      - elasticsearch

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8003
    depends_on:
      - output_module
    profiles: ["with-frontend"]
